- hosts: tag_type_nginx 
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

- name: Configure instance(s)
  hosts: tag_type_nginx
  become: True
  gather_facts: True
  tasks:
    # - name: update apt cache
    #   become: yes
    #   package: update_cache=yes
    
    - name: install aptitude
      # on Debian Jessie aptitude is not installed by default, without it apt-get upgrade fails
      become: yes
      package: name=aptitude state=installed
    
    # - name: upgrade apt packages
    #   become: yes
    #   package: upgrade=full
    
    - name: install dev tools and libraries
      become: yes
      package: name={{ item }} state=installed
      with_items:
        - build-essential
        - git
        - curl
        - openssl
        - libreadline6
        - libreadline6-dev
        - zlib1g
        - zlib1g-dev
        - libssl-dev
        - nginx

- name: Install Rails App
  hosts: tag_group_a
  gather_facts: True
  roles:
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.7', 'ruby-2.4.1'],
        rvm1_user: 'ubuntu'
      }
  tasks:
    - name: clone rails app
      git:
        repo: 'https://github.com/LEARNAcademy/learn-rails.git'
        dest: '/var/www/html/learn-rails'
        version: master
    - name: bundle
      shell: '/home/ubuntu/.rvm/wrappers/ruby-2.4.1/bundle'
      args:
        chdir: '/var/www/html/learn-rails'
    - copy: src=./files/rails.service dest=/etc/systemd/system/rails.service owner=root group=root
      become: yes
    - name: start rails
      systemd: state=started name=rails daemon_reload=yes

- name: Proxy config 
  hosts: tag_group_a
  gather_facts: True
  tasks: 
    - copy: src=./files/apps.conf dest=/etc/nginx/sites-available/default owner=root group=root
      become: yes
    - name: restart nginx
      become: yes
      service: name=nginx enabled=yes state=restarted

